# hyprland.conf
# Monitor and general settings
monitor=,preferred,auto,1
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    # Border color using alpha
    col.active_border = rgba(efae64bf) # bf is ~0.75
    col.inactive_border = rgba(efae6455)
}

# Example decoration settings
decoration {
    rounding = 0
    blur = yes
    blur_size = 3
    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(00000044)
}
bind = SUPER, space, exec, quickshell -p ~/.config/quickshell/omarchy-pop/shell.qml
