[menu]
border = "#efae64"
border-alpha = 0.7
background = "#333333"
selected-background = "#5b7a75"
selected-background-alpha = 0.1
selected-border = "#8dc3bb"
selected-border-alpha = 0.3
selected-border-width = 1
selected-text = "#8dc3bb"
scrim = "#2b2a27"
scrim-alpha = 0.0
