# pop — tmux theme
# add to ~/.config/tmux/tmux.conf (or source it)

set -g mode-style "fg=#d1ccc3,bg=#505048"
set -g message-style "fg=#d1ccc3,bg=#505048"
set -g message-command-style "fg=#d1ccc3,bg=#505048"
set -g pane-border-style "fg=#505048"
set -g pane-active-border-style "fg=#909080"
set -g status-style "fg=#d1ccc3,bg=#34332f"
set -g status-left-style "fg=#34332f,bg=#909080"
set -g status-right-style "fg=#d1ccc3,bg=#34332f"

set -g status-left "#[fg=#34332f,bg=#909080] #S #[default]"
set -g status-right "#[fg=#909080,bg=#34332f] %H:%M #[default]"
set -g window-status-style "fg=#909080,bg=#34332f"
set -g window-status-current-style "fg=#34332f,bg=#d1ccc3"
set -g window-status-separator ""

set -g clock-mode-colour "#d1ccc3"
set -g copy-mode-current-match-style "bg=#686860,fg=#34332f"
